version: '3.7'

services:
  hub:
    image: selenium/hub:3.141.59-iron
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.141.59-iron
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
      START_XVFB: "false"
    deploy:
        replicas: 5
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'

  tester:
    image: loadtester:0.1
    tty: true
    # command: bash
    command: ./wait_for_grid.sh pytest
    volumes:
      - ./:/usr/src/app
